### ISSUE TITLE
Maybe move holidays / calendars to their own mini package

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/almanac#13]
This would be nice because it could have its own file structure, one file for each calendar / holiday. And more importantly it could have its own release cycle. I have a feeling that almanac will probably be pretty stable, while the extra calendar / holiday package could require more releases as people want ad hoc holiday support. Separating it out might prove useful

**Comment by jameslairdsmith** [comment]
I think this is a very good idea. I agree with the reasons you’ve mentioned and I have a few in addition:

1. If the list of holidays were to become more extensive (which I think is a good idea), it would end up adding quite a lot of functions to the namespace and documentation. This isn't a massive problem, but it seems better as something done deliberately by users, rather than done automatically when they load `almanac`.
1. It will make for easier organisation of issues, requests and other admin, which then won't get lumped together with those of `almanac`.
1. The new package could be called `vacationr` and that would be awesome.

**Comment by DavisVaughan** [comment]
I also kind of like {sunset}

**Comment by DavisVaughan** [comment]
Moving to vacation! https://github.com/DavisVaughan/vacation
