### ISSUE TITLE
intra-day recurrence rules

### ISSUE THREAD

**Issue by earowang** [DavisVaughan/almanac#69]
Hi Davis,

Do you plan to support `POSIXct`, `hms`/`difftime` for intra-day recurrence rules? The {almanac} can be a backbone of tsibble's calendar feature.

**Comment by DavisVaughan** [comment]
It isn’t planned for the first release. Maybe in the far future, but it would likely require a pretty different approach because currently all events between `since` and `until` are generated and stored in the cache. This isn’t bad when the finest granularity is daily, but for a `secondly()` rule this could be painful. Maybe it’s okay though, and if secondly is used then it’s up to the user to ensure they aren’t generating a rule with a massive amount of events

I’ve also been able to totally avoid pain with time zones right now, which would have to be dealt with if this was added. The JavaScript library seems to have the approach where only UTC is really supported, which seems reasonable but confusing sometimes when you’re in a DST gap.

In the far future I’d like to swap the JavaScript dependency for a C one and use libical. From what I can tell they have better time zone support (and also support non Gregorian calendars so things like Chinese New Year could be implemented). That will require a decent amount of work to make sure it can be installed properly on all platforms

**Comment by DavisVaughan** [comment]
Does the calendar/holiday part of tsibble really support intra day? https://github.com/tidyverts/tsibble/blob/master/R/holiday.R

Update: I could see business hours being useful

**Comment by DavisVaughan** [comment]
You should also take a look at vacation if you haven’t yet, it’s incomplete but that’s where the holiday part of this will go, and it probably what tsibble would use https://github.com/DavisVaughan/vacation

**Comment by earowang** [comment]
Thanks Davis. Good to know your plan. I'm actually referring to this issue https://github.com/tidyverts/tsibble/issues/18

Tsibble's holiday functions are just for australia holidays, and independent from the tsibble data structure.

**Comment by DavisVaughan** [comment]
I have decided that almanac won't support intra day events, but I did add a full holiday/calendar API in #96 and #97
